version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/skillbridge
      - DATABASE_USERNAME=skillbridge_user
      - DATABASE_PASSWORD=skillbridge_password
      - JWT_SECRET=your-super-secure-jwt-secret-key-here-make-it-long-and-random
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - db
    networks:
      - skillbridge-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=skillbridge
      - POSTGRES_USER=skillbridge_user
      - POSTGRES_PASSWORD=skillbridge_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skillbridge-network

volumes:
  postgres_data:

networks:
  skillbridge-network:
    driver: bridge 