spring:
  datasource:
    url: jdbc:postgresql://ep-proud-cherry-a1x132v7-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_SzQ2u6empEFN
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true