spring:
  datasource:
    url: jdbc:postgresql://ep-proud-cherry-a1x132v7-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_SzQ2u6empEFN
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080

jwt:
  secret: coolfooliscreatingthisprojecton10062025
  expiration: 86400000 # 24 hours in milliseconds
